### ISSUE TITLE
Undefined method 'exists?' in get_installation method

### ISSUE THREAD

**Issue by wojciech-zygmuntowicz** [imagov/keycloak#47]
Probably just a typo, but when using the gem without manually generated config/keycloak.json, but only using an initializer file config/initializers/keycloak.rb I couldn't use Keycloak::Client.get_token method, because of error:

```
/home/XYZ/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/keycloak-3.2.2/lib/keycloak.rb:339:in `get_installation': undefined method `exists?' for File:Class (NoMethodError)

        if File.exists?(Keycloak.installation_file)
               ^^^^^^^^
Did you mean?  exist?

```

**Comment by RazvanFarte** [comment]
Reproduced in my env too after upgrading from ruby 2.7.6 to 3.2.2
.exists? has been removed in 3.2.0 as in the release notes: https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

> The following deprecated methods are removed.
> Dir.exists? [[Feature #17391](https://bugs.ruby-lang.org/issues/17391)]
> File.exists? [[Feature #17391](https://bugs.ruby-lang.org/issues/17391)]

The fix in the PR looks good to me. It should be merged in the master.

**Comment by AndreyPnm** [comment]
Reproduced same error after upgrading to ruby:3.2.4 from ruby:2.7.8

```
(irb):7:in `<main>': undefined method `exists?' for File:Class (NoMethodError)

        if File.exists?(Keycloak.installation_file)
               ^^^^^^^^
Did you mean?  exist?
```
